CREATE TEMP TABLE company_profiles_staging (
    symbol VARCHAR(20),
    price TEXT,
    beta TEXT,
    volAvg TEXT,
    mktCap TEXT,
    lastDiv TEXT,
    range VARCHAR(50),
    changes TEXT,
    companyName VARCHAR(255),
    currency VARCHAR(10),
    cik VARCHAR(20),
    isin VARCHAR(20),
    cusip VARCHAR(20),
    exchange VARCHAR(100),
    exchangeShortName VARCHAR(50),
    industry TEXT,
    website TEXT,
    description TEXT,
    ceo VARCHAR(255),
    sector VARCHAR(100),
    country VARCHAR(10),
    fullTimeEmployees TEXT,
    phone VARCHAR(30),
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    zip VARCHAR(20),
    dcfDiff TEXT,
    dcf TEXT,
    image TEXT,
    ipoDate TEXT,
    defaultImage TEXT,
    isEtf TEXT,
    isActivelyTrading TEXT,
    isAdr TEXT,
    isFund TEXT
);

COPY company_profiles_staging
-- IMPORTANT NOTE: SET YOUR CSV FILE PATH HERE
FROM '/tmp/company_profiles.csv'
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

INSERT INTO company_profiles (
    symbol, price, beta, volAvg, mktCap, lastDiv, range, changes, companyName,
    currency, cik, isin, cusip, exchange, exchangeShortName, industry, website,
    description, ceo, sector, country, fullTimeEmployees, phone, address, city,
    state, zip, dcfDiff, dcf, image, ipoDate, defaultImage, isEtf,
    isActivelyTrading, isAdr, isFund, data_load_date
)
SELECT
    s.symbol,
    NULLIF(s.price, '')::NUMERIC(19, 4),
    NULLIF(s.beta, '')::NUMERIC(12, 6),
    NULLIF(s.volAvg, '')::NUMERIC(20, 4),
    NULLIF(s.mktCap, '')::BIGINT,
    NULLIF(s.lastDiv, '')::NUMERIC(19, 4),
    s.range,
    NULLIF(s.changes, '')::NUMERIC(19, 4),
    s.companyName,
    s.currency,
    s.cik,
    s.isin,
    s.cusip,
    s.exchange,
    s.exchangeShortName,
    s.industry,
    s.website,
    s.description,
    s.ceo,
    s.sector,
    s.country,
    NULLIF(regexp_replace(s.fullTimeEmployees, '[^0-9]', '', 'g'), '')::BIGINT,
    s.phone,
    s.address,
    s.city,
    s.state,
    s.zip,
    NULLIF(s.dcfDiff, '')::NUMERIC(19, 5),
    NULLIF(s.dcf, '')::NUMERIC(19, 5),
    s.image,
    NULLIF(s.ipoDate, '')::DATE,
    NULLIF(LOWER(s.defaultImage), '')::BOOLEAN,
    NULLIF(LOWER(s.isEtf), '')::BOOLEAN,
    NULLIF(LOWER(s.isActivelyTrading), '')::BOOLEAN,
    NULLIF(LOWER(s.isAdr), '')::BOOLEAN,
    NULLIF(LOWER(s.isFund), '')::BOOLEAN,
    CURRENT_DATE
FROM company_profiles_staging s
ON CONFLICT (symbol, data_load_date) DO UPDATE SET
    price = NULLIF(EXCLUDED.price::TEXT, '')::NUMERIC(19, 4),
    beta = NULLIF(EXCLUDED.beta::TEXT, '')::NUMERIC(12, 6),
    volAvg = NULLIF(EXCLUDED.volAvg::TEXT, '')::NUMERIC(20, 4),
    mktCap = NULLIF(EXCLUDED.mktCap::TEXT, '')::BIGINT,
    lastDiv = NULLIF(EXCLUDED.lastDiv::TEXT, '')::NUMERIC(19, 4),
    range = EXCLUDED.range,
    changes = NULLIF(EXCLUDED.changes::TEXT, '')::NUMERIC(19, 4),
    companyName = EXCLUDED.companyName,
    currency = EXCLUDED.currency,
    cik = EXCLUDED.cik,
    isin = EXCLUDED.isin,
    cusip = EXCLUDED.cusip,
    exchange = EXCLUDED.exchange,
    exchangeShortName = EXCLUDED.exchangeShortName,
    industry = EXCLUDED.industry,
    website = EXCLUDED.website,
    description = EXCLUDED.description,
    ceo = EXCLUDED.ceo,
    sector = EXCLUDED.sector,
    country = EXCLUDED.country,
    fullTimeEmployees = NULLIF(regexp_replace(EXCLUDED.fullTimeEmployees::TEXT, '[^0-9]', '', 'g'), '')::BIGINT,
    phone = EXCLUDED.phone,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    dcfDiff = NULLIF(EXCLUDED.dcfDiff::TEXT, '')::NUMERIC(19, 5),
    dcf = NULLIF(EXCLUDED.dcf::TEXT, '')::NUMERIC(19, 5),
    image = EXCLUDED.image,
    ipoDate = NULLIF(EXCLUDED.ipoDate::TEXT, '')::DATE,
    defaultImage = NULLIF(LOWER(EXCLUDED.defaultImage::TEXT), '')::BOOLEAN,
    isEtf = NULLIF(LOWER(EXCLUDED.isEtf::TEXT), '')::BOOLEAN,
    isActivelyTrading = NULLIF(LOWER(EXCLUDED.isActivelyTrading::TEXT), '')::BOOLEAN,
    isAdr = NULLIF(LOWER(EXCLUDED.isAdr::TEXT), '')::BOOLEAN,
    isFund = NULLIF(LOWER(EXCLUDED.isFund::TEXT), '')::BOOLEAN;

DROP TABLE company_profiles_staging;